[package]
name = "wordle"
authors = ["Hobbs Bros."]
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = "0.16.2"

[[bin]]
name = "wordler"
path = "src/wordler.rs"

[[bin]]
name = "benchmark"
path = "src/benchmark.rs"

[lib]
name = "util"
path = "src/util/mod.rs"